### ISSUE TITLE
193页勘误

### ISSUE THREAD

**Issue by wayne-cheng** [kubeguide/K8sDefinitiveGuide-V4-corrigendum#6]
## 书名

- [x] Kubernetes 权威指南（第四版）

## 问题所在页码
193
## 问题描述
nginx-deployment.yaml文件缺少selector配置项，应在倒数第15行添加：

```yaml
selector:
    matchLabels:
         app: nginx
```

否则无法创建Deployment，会提示`missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec`的错误。（我使用的k8s版本：v1.14.1）
## 相关链接
